# Training Configuration
training:
  learning_rate: 0.001
  n_epochs: 50
  loss: "BCE"
  post_processor: "JOINT"
  batch_size: 1
  num_workers: 0
  
  # Early stopping
  early_stop_patience: 10
  early_stop_min_delta: 0.0001

  # Learning rate scheduler
  scheduler_factor: 0.2
  scheduler_patience: 5

  # Data splits
  test_size: 0.2

  # Pretrained Model (place in the pretrained directory)
  pretrained_model: "tcn_bl/tcn_bl-run2.ckpt"

# Experiment Tracking
experiment:
  project_name: "TCN_FT"
  wandb_api_key: "your_wandb_api_key"
  ckpt_name: "tcn_carnatic_ft"